const newa=[
    {id:1,
    tag:'sport',
    img:'./piblic/news1.jpg',
    date: new Date(2020,10,4,11,58),
    title:"Требониан Галл просиходил из странного рода.В конце правления императора"+"Деция Траяна он занимал должность легата",
    description:"Будущий император Гай Вибий Требониан Галл родился около 206 года.",
    likesCount: 11500,
    commentsCount:1500,
    isLiked:true,
    },
    {id:2,
        tag:'nature',
        img:'./piblic/news1.jpg',
        date: new Date(2021,10,4,11,58),
        title:"China is using satellites to police the protection of nature — but will it work?",
        description:"China's government is the first to use satellites to monitor land set aside for conservation to ensure its protection from illegal development. Scientists hope that the move will safeguard ecologically important habitats and provide a model of remote-sensing use for conservation that other countries could follow.",
        likesCount: 11000,
        commentsCount:100,
        isLiked:true,
        },
        {id:3,
            tag:'nature',
            img:'./piblic/news1.jpg',
            date: new Date(2021,10,4,11,58),
            title:"China is using satellites to police the protection of nature — but will it work?",
            description:"China's government is the first to use satellites to monitor land set aside for conservation to ensure its protection from illegal development. Scientists hope that the move will safeguard ecologically important habitats and provide a model of remote-sensing use for conservation that other countries could follow.",
            likesCount: 11000,
            commentsCount:100,
            isLiked:true,
            },
];